model:
  base_learning_rate: 4.5e-06
  params: 
    cond_stage_config: 
      params: 
        down_factor: 16
        n_embed: 1024
      target: taming.modules.misc.coord.CoordStage
    cond_stage_key: coord
    first_stage_config: 
      params: 
        ckpt_path: logs/2021-02-24T18-54-51_faceshq_vqgan/checkpoints/last.ckpt
        ddconfig: 
          attn_resolutions: 
            - 16
          ch: 128
          ch_mult: 
            - 1
            - 1
            - 2
            - 2
            - 4
          double_z: false
          dropout: 0.0
          in_channels: 3
          num_res_blocks: 2
          out_ch: 3
          resolution: 256
          z_channels: 256
        embed_dim: 256
        lossconfig: 
          target: taming.modules.losses.DummyLoss
        n_embed: 1024
      target: taming.models.vqgan.VQModel
    transformer_config: 
      params: 
        block_size: 512
        n_embd: 1024
        n_head: 16
        n_layer: 24
        vocab_size: 1024
      target: taming.modules.transformer.mingpt.GPT
  target: taming.models.cond_transformer.Net2NetTransformer

data:
  params:
    batch_size: 2
    num_workers: 8
    train:
      params:
        coord: true
        crop_size: 256
        size: 256
      target: taming.data.faceshq.FacesHQTrain
    validation:
      params:
        coord: true
        crop_size: 256
        size: 256
      target: taming.data.faceshq.FacesHQValidation
  target: main.DataModuleFromConfig